name: Workflow Job

on: 
  push:
    branches:
      - master
      - release
      - develop
      - tests
  workflow_dispatch:

env:
  FIO: Балашов Владимир Андреевич
  GROUP_NUMBER: M3113
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$FIO $GROUP_NUMBER ${{ github.actor }}"
      - uses: actions/setup-python@v4
        with:
            python-version: '3.13'
            
      - run: pip install -r ./requirements.txt
      - run: pytest
      - run: pylint *.py
      - run: pylint tests/*.py
